//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Cake.TeamCity")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0+0.Branch.master.Sha.51f5232a77c1a944a97b26b463fb3cad7e6b91f2")]
[assembly: AssemblyCopyright("Copyright (c) Richard Simpson 2016")]
